all:
  hosts:
    node1:
      ansible_host: 192.168.0.184
      ip: 192.168.0.184
    node2:
      ansible_host: 192.168.0.176
      ip: 192.168.0.176
    node3:
      ansible_host: 192.168.0.251
      ip: 192.168.0.251
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
